[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@uniswap/=lib/", "@openzeppelin/openzeppelin=lib/openzeppelin-contracts", "@solmate/=lib/solmate"]
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
